### ISSUE TITLE
无法正常初始化

### ISSUE THREAD

**Issue by Dg32z** [Love-MHDF/MHDF-Verify#1]
C:\Users\Administrator\Desktop\AdvancedAuth>"D:\jdk-18\bin\java.exe" -jar [梦之验证]MHDF-Verify-Server-1.0.0-SNAPSHOT.jar
15:10:28.493 [main] INFO com.zaxxer.hikari.HikariDataSource -- HikariPool-1 - Starting...
15:10:28.944 [main] INFO com.zaxxer.hikari.pool.HikariPool -- HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@6d07a63d
15:10:28.948 [main] INFO com.zaxxer.hikari.HikariDataSource -- HikariPool-1 - Start completed.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
Caused by: java.sql.SQLSyntaxErrorException: BLOB, TEXT, GEOMETRY or JSON column 'Log' can't have a default value
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at cn.chengzhiya.mhdfverify.util.DatabaseUtil.runSQLUpdate(DatabaseUtil.java:75)
        at cn.chengzhiya.mhdfverify.util.DatabaseUtil.initDatabase(DatabaseUtil.java:59)
        at cn.chengzhiya.mhdfverify.Application.main(Application.java:27)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 4 more

**Comment by ChengZhiMeow** [comment]
fix
